references:
  workspace_root: &workspace_root /home/circleci/my-workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

version: 2
jobs:
  install:
    working_directory: *workspace_root
    docker:
      - image: circleci/node:10
    steps:
      - checkout

      - run: npm ci

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - node_modules/

  build:
    working_directory: *workspace_root
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - *attach_workspace

      - run: npm run build

  test:
    working_directory: *workspace_root
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - *attach_workspace

      - run: npm run test
  
  lint:
    working_directory: *workspace_root
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - *attach_workspace

      - run: |
          npm run lint
          npm run prettier:check

workflows:
  version: 2
  build-deploy:
    jobs:
      - install
      - build:
          requires:
            - install
      - test:
          requires:
            - install
      - lint:
          requires:
            - install
